version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd -B -ntp{{else}}./mvnw -B -ntp{{end}}'
  SLEEP: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
  default:
    cmds:
      - task: test

  test:
    deps: [ format ]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  release-perform:
    cmds:
      - "{{.MVNW}} release:clean release:prepare"
      - "{{.MVNW}} release:perform"

  deploy-local:
    deps: [ test ]
    cmds:
      - "{{.MVNW}} deploy"

  deploy-central:
    deps: [ test ]
    cmds:
      - "{{.MVNW}} deploy -Prelease"

  sonar:
    cmds:
      - "{{.MVNW}} sonar:sonar -Dsonar.token=$SONAR_TOKEN" # read from shell env

  build-docker:
    cmds:
      - "{{.MVNW}} -pl rose/rose-upms spring-boot:build-image -DskipTests"
      - "{{.MVNW}} -pl rose/rose-monitor spring-boot:build-image -DskipTests"
      - "{{.MVNW}} -pl rose/rose-gateway spring-boot:build-image -DskipTests"

  start_infra:
    cmds:
      - "docker compose -f docker-compose.yml up -d"

  stop_infra:
    cmds:
      - "docker compose -f docker-compose.yml stop"
      - "docker compose -f docker-compose.yml rm -f"

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start:
    deps: [ build ]
    cmds:
      - "docker compose -f docker-compose.yml -f docker-compose-app.yml up -d"

  stop:
    cmds:
      - "docker compose -f docker-compose.yml -f docker-compose-app.yml stop"
      - "docker compose -f docker-compose.yml -f docker-compose-app.yml rm -f"

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  start_monitor:
    cmds:
      - "docker compose -f docker-compose-monitor.yml up -d"

  stop_monitor:
    cmds:
      - "docker compose -f docker-compose-monitor.yml stop"
      - "docker compose -f docker-compose-monitor.yml rm -f"

  restart_monitor:
    cmds:
      - task: stop_monitor
      - task: sleep
      - task: start_monitor

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP}} {{.DURATION}}"
