name: Auto Approve

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  auto-approve:
    uses: rosestack/.github/.github/workflows/auto-approve.yml@main
    secrets: inherit
