name: Build and Deploy Release

##
## Automates the release process
## 1. Run `./list-changes.sh` and update the changelog.md.
## 2. Run `./prepare-release.sh`
## 3. Create PR, merge PR
## 4. Run `git push origin --tags`
##

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: rosestack/.github/.github/workflows/maven-release.yml@main
    secrets: inherit
