name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  update_release_draft:
    uses: rosestack/.github/.github/workflows/release-drafter.yml@main
